/**
 * PawMeBot Community — Seed Data
 * Historical content extracted from WhatsApp, Google Drive, git history, meeting notes.
 */

export interface SeedPost {
  id: string;
  title: string;
  content: string;
  author: 'ashok' | 'pawme_bot' | 'prithu' | 'lalith' | 'hitesh' | 'ameya' | 'community';
  authorName: string;
  pillar: 'build_in_public' | 'product_showcase' | 'founder_voice' | 'community_prompt' | 'market_context' | 'design' | 'media' | 'software' | 'milestone' | 'partnership' | 'manufacturing';
  tags: string[];
  upvotes: number;
  commentCount: number;
  createdAt: string;
  sourceType: 'whatsapp' | 'meeting_notes' | 'dev_log' | 'press' | 'community' | 'git_history';
  imageUrls?: string[];
  platforms: 'x' | 'telegram' | 'both';
  status: 'published' | 'draft';
}

export interface SeedTimelineEvent {
  id: string;
  date: string;
  title: string;
  description: string;
  category: 'prototype' | 'design' | 'firmware' | 'software' | 'manufacturing' | 'media' | 'partnership' | 'award' | 'milestone';
  sourceType: 'whatsapp' | 'meeting_notes' | 'dev_log' | 'press' | 'git_history';
}

export interface SeedApp {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  description: string;
  logoUrl: string;
  screenshotUrls: string[];
  features: string[];
  techStack: string[];
  githubUrl?: string;
  appStoreUrl?: string;
  playStoreUrl?: string;
  websiteUrl?: string;
  status: 'active' | 'beta' | 'development' | 'archived';
  createdAt: string;
}

// =============================================================================
// 40 COMMUNITY POSTS — Full journey from July 2025 to May 2026
// =============================================================================

export const SEED_POSTS: SeedPost[] = [
  // ── ORIGIN STORY ──
  {
    id: 'post-origin-1',
    title: 'The BB-8 Dream: How It All Started 🎬',
    content: `It started with a simple question: what if BB-8 could actually see, think, and care for your pet?\n\nNot just a rolling ball with an app. A real AI companion that understands its environment, responds to emotions, and connects with your pet.\n\nOn July 21, 2025, I created a WhatsApp group called "Rolling Robot" and shared a YouTube video of an open-source spherical robot. That was day one.\n\nFast forward: 8 countries, 4 prototypes, 355 build photos, 27 dev videos, 1 patent filed, and a team spread across India, Hong Kong, and beyond.\n\nThis is the story of PawMe.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['origin_story', 'bb8', 'build_in_public', 'hardware', 'journey'],
    upvotes: 156,
    commentCount: 45,
    createdAt: '2025-07-21T13:11:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-origin-2',
    title: 'Day 1: Sharing Everything Open-Source 📦',
    content: `Within the first hour of starting this project, I shared:\n\n→ The full mechanical video reference\n→ PCBA schematics and design files\n→ Complete firmware source code (GEMCAM_AI on GitHub)\n→ A Perplexity research link on the technology\n→ The PRD document (co-created with the team)\n\nWhy? Because this project is open-source from day one. If we want to build a community around AI pet robots, we need to share everything.\n\nThe goal: replicate the spherical rolling robot design in 2 weeks, then add AI vision, voice Q&A, and emotional intelligence on top.\n\nLet's see how this goes.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'build_in_public',
    tags: ['open_source', 'day1', 'pcba', 'firmware', 'prd'],
    upvotes: 89,
    commentCount: 22,
    createdAt: '2025-07-21T18:48:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── PATENT & DESIGN STRATEGY ──
  {
    id: 'post-patent-1',
    title: 'Patent Evasion: How We Avoided Sphero/Disney\'s IP 🧠',
    content: `Here's a key strategic decision from week one:\n\nSphero (owned by Disney) holds patents on certain spherical rolling robot mechanisms. We identified this on day 3 and immediately pivoted our approach.\n\nInstead of a full-sphere rolling mechanism, we proposed:\n→ Top PCBA with WiFi/AI separate from the bottom wheel base\n→ IR transmitter sending movement commands to bottom motors\n→ Tilting head mechanism on top for expressions\n→ Magnet-based head attachment (not mechanical)\n\nThis way we get the BB-8 aesthetic AND personality without infringing on existing patents. Later, we filed a provisional patent for our unique tilting head mechanism.\n\nHardware is hard. Hardware IP is harder. Plan accordingly.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'product_showcase',
    tags: ['patent', 'sphero', 'ip', 'strategy', 'design'],
    upvotes: 134,
    commentCount: 38,
    createdAt: '2025-07-24T00:01:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── TEAM FORMATION ──
  {
    id: 'post-team-1',
    title: 'Team Assembly: Prithu, Hitesh, and the Kickstarter-First Mindset 🤝',
    content: `By day 4, we had our core team forming:\n\n→ Prithu Hazarika: Mechanical design, project coordination, and Kickstarter campaign lead\n→ Hitesh Suthar: Product design, storytelling, and art direction for the Kickstarter video\n→ Myself (Ashok): ESP32 firmware, AI integration, sourcing, and overall product direction\n\nThe key insight from Prithu: "Don't build the robot first. Build the story first."\n\nWe spent days analyzing successful Kickstarter campaigns:\n→ Loona Petbot (our main benchmark)\n→ KEYI Technology\n→ Rux Robot\n→ Little Sophia\n\nWe created a Miro board for visual research, storyboarding, and feature prioritization. The Kickstarter video became almost as important as the hardware itself.\n\nHardware startups die without story. Remember that.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['team', 'kickstarter', 'prithu', 'hitesh', 'miro', 'storytelling'],
    upvotes: 112,
    commentCount: 29,
    createdAt: '2025-07-26T08:40:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-team-2',
    title: 'Behind the Scenes: Our Miro Board Research Process 📋',
    content: `Here's how we approached the product definition:\n\n1. Studied every successful AI pet/moveable robot on Kickstarter\n2. Analyzed their video structure, messaging, and emotional hooks\n3. Identified what features made products "backable" vs just "interesting"\n4. Created user personas for our target customer\n5. Reverse-engineered the pricing strategy from successful campaigns\n\nKey finding: The most successful campaigns don't sell features. They sell a feeling. The feeling of having a pet that's always there, always aware, always caring.\n\nThat's what PawMe needs to be.\n\n#build_in_public #product_design #kickstarter #research`,
    author: 'prithu',
    authorName: 'Prithu Hazarika',
    pillar: 'market_context',
    tags: ['miro', 'research', 'kickstarter', 'product_design', 'ux'],
    upvotes: 78,
    commentCount: 15,
    createdAt: '2025-07-25T20:49:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── FIRMWARE JOURNEY ──
  {
    id: 'post-firmware-1',
    title: 'Firmware Wars: ESP-IDF vs Arduino (The Great Merge Conflict) ⚡',
    content: `Here's a technical challenge that consumed weeks of our development:\n\nThe open-source ESP-ROLL project provides:\n→ OpenAI RTC (Real-Time Communication) code — written in ESP-IDF\n→ OpenAI Vision/Q&A code — written in Arduino\n\nThese two codebases use completely different SDKs, build systems, and approaches. Merging them onto a single ESP32 was... painful.\n\nOur firmware engineer Lalith Kumar spent days trying to get audio recording working from the ESP32 to send to OpenAI's API. Postman worked fine. ESP32 kept throwing errors.\n\nEventually we made the tough decision: rebuild from scratch using the best reference from both codebases, rather than trying to merge incompatible systems.\n\nLesson: choosing the right SDK/framework at the start saves months of pain later.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'build_in_public',
    tags: ['firmware', 'esp32', 'esp_idf', 'arduino', 'openai', 'technical_deep_dive'],
    upvotes: 145,
    commentCount: 52,
    createdAt: '2025-08-27T18:33:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-firmware-2',
    title: 'First Working OpenAI QA on ESP32 — Ask the Robot What It Sees! 👁️',
    content: `BREAKTHROUGH: Lalith got the OpenAI Image Q&A working on the ESP32!\n\nHere's how it works:\n1. Press "Start Recording" on the web UI\n2. Speak your question to the robot\n3. Press "Stop Recording"\n4. Audio is sent to OpenAI → transcribed\n5. Camera captures an image simultaneously\n6. Both are sent to OpenAI Vision API\n7. The answer is played back through the speaker\n\nThe robot can literally see its environment and answer questions about it. "What do you see?" → "I see a table with a laptop and several electronic components."\n\nThis is the core feature of PawMe. Not just a rolling robot — a robot that understands.\n\nWeb UI pages built:\n→ Start/Stop recording\n→ Firmware toggle (ESP-ROLL mode vs OpenAI QA mode)\n\nLive stream window with game controller overlay for manual driving.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'product_showcase',
    tags: ['firmware', 'openai', 'vision', 'qna', 'esp32', 'breakthrough'],
    upvotes: 198,
    commentCount: 67,
    createdAt: '2025-09-04T15:08:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-firmware-3',
    title: 'Web Controller: Driving Your Robot from a Browser 🎮',
    content: `We built a web-based controller that runs directly on the ESP32:\n\n→ Live camera stream (MJPEG over HTTP)\n→ Virtual joystick in the browser for movement control\n→ Start/Stop audio recording for OpenAI Q&A\n→ Firmware mode toggle (rolling mode vs AI mode)\n→ Settings page for WiFi configuration\n\nThe ESP32 hosts its own web server. Connect to the robot's WiFi, open a browser, and you have full control — camera, movement, and AI conversation.\n\nEventually this becomes the mobile app, but for now the web controller lets us demo to anyone with a phone.\n\nStack: ESP32 async web server, WebSocket for camera stream, REST API for commands.`,
    author: 'lalith',
    authorName: 'Lalith Kumar',
    pillar: 'build_in_public',
    tags: ['web_controller', 'esp32', 'camera_stream', 'websocket', 'demo'],
    upvotes: 112,
    commentCount: 31,
    createdAt: '2025-09-05T15:07:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── PROTOTYPE ITERATIONS ──
  {
    id: 'post-proto-1',
    title: 'Prototype v0.1: From Tape and Glue to First Movement 🔧',
    content: `The first physical prototype looked... rough.\n\nLots of tape. Lots of glue. Components held together with hope. But it moved.\n\nPrithu's team in Hyderabad assembled the first ESP-ROLL unit using:\n→ 3D-printed internal frame\n→ ESP-32 dev board\n→ Motor driver ICs (despite wrong parts being shipped due to typhoon!)\n→ 1000mAh battery\n→ Transparent spherical enclosure (sourced from — nowhere in India, had to get from overseas)\n\nKey lesson: The 100mm transparent ball was nearly impossible to source in India. Searched every domestic site. Christmas decorations. Nothing. Had to ask a friend visiting from overseas to bring it.\n\nFirst unit was sent to Hong Kong via a friend traveling from Hyderabad. Carried in hand luggage (lithium battery restrictions!).\n\nIt's not pretty. But it works. And that's what matters for v0.1.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'build_in_public',
    tags: ['prototype', 'v0.1', 'first_build', 'hyderabad', 'sourcing', '3d_printing'],
    upvotes: 167,
    commentCount: 43,
    createdAt: '2025-09-18T10:59:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-proto-2',
    title: 'Custom PCBA: From Breadboard to Designed Circuit Board 🏭',
    content: `Moving from dev boards to custom PCB design.\n\nSumit completed the custom PCBA layout for PawMe. Key design decisions:\n\n→ Consolidated ESP32, motor drivers, power management, camera interface onto single board\n→ Component placement optimized for the cylindrical body shape\n→ All modules routed and ready for manufacturing\n\nThe design went from:\n→ Breadboard prototype (weeks of wiring)\n→ Dev board integration (still messy)\n→ Custom PCBA (clean, reproducible, manufacturable)\n\nWe ordered 10 initial boards. They arrived, components were soldered, and we began assembly.\n\nThis is the difference between a science project and a product.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'build_in_public',
    tags: ['pcba', 'pcb_design', 'manufacturing', 'sumit', 'hardware'],
    upvotes: 93,
    commentCount: 18,
    createdAt: '2025-10-02T02:19:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-proto-3',
    title: 'New Mechanical Design: Starting From Scratch (Again) 🎨',
    content: `Major pivot: After assembling the ESP-ROLL-based prototype, Prithu\'s team made a critical decision.\n\nThe existing 3D files from the open-source project? Nearly impossible to build upon. Too many compromises. Too difficult to modify.\n\nDecision: Design ALL mechanical plastic parts from scratch.\n\nAmeya Mistry (our industrial designer) joined the team and began designing the body, head, charging dock, and treat dispenser — all from a blank canvas.\n\nThis added cost. This added time. But it was the right call. Building on someone else's mechanical design is like building on rented land.\n\nNew mechanical design goals:\n→ Rounded, friendly aesthetic (not angular)\n→ Single color body for clean look\n→ Display/face as the "soul" of the robot\n→ Easy assembly and repair`,
    author: 'prithu',
    authorName: 'Prithu Hazarika',
    pillar: 'design',
    tags: ['mechanical_design', 'ameya_mistry', 'pivot', 'from_scratch', 'industrial_design'],
    upvotes: 124,
    commentCount: 35,
    createdAt: '2025-09-20T21:40:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── KICKSTARTER VIDEO ──
  {
    id: 'post-video-1',
    title: 'Shooting the Kickstarter Video: 52 Clips and a Story to Tell 🎬',
    content: `We shot the Kickstarter video in November 2025.\n\nThe plan:\n→ Shoot on mobile phones (not professional equipment)\n→ Edit and stitch at our end\n→ Tell a story, not just show a product\n\nThe video covers 6 parts:\n1. Intro / Hook\n2. Product Overview\n3. Design Process\n4. Electronics & Firmware\n5. Manufacturing & Assembly\n6. Final Reveal\n\nOver 52 video clips were shot across multiple days. The team uploaded everything to Google Drive for review. During the shoot:\n→ Ambient noise was a challenge (solved with music overlay)\n→ Multiple angles of each shot for flexibility\n→ Close-ups of PCBA assembly, 3D printing, testing\n\nThe reference videos we studied all had one thing in common: they made you FEEL something. That's the bar we're aiming for.`,
    author: 'prithu',
    authorName: 'Prithu Hazarika',
    pillar: 'media',
    tags: ['kickstarter', 'video', 'shooting', 'storytelling', '52_clips'],
    upvotes: 142,
    commentCount: 39,
    createdAt: '2025-11-12T19:51:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── INDUSTRIAL DESIGN ──
  {
    id: 'post-design-1',
    title: 'Ameya Mistry Joins: Industrial Design Meets Robotics 🎨',
    content: `Big announcement: Ameya Mistry has joined the PawMe project as our industrial designer.\n\nAmeya is working on:\n→ Overall product form factor and aesthetics\n→ Head design with LED matrix face\n→ Body proportions and character\n→ Charging dock design\n→ Treat dispenser mechanism\n\nHis first design explorations were stunning. Multiple head shapes, body proportions, color options. The team debated everything:\n\n→ Should the head be a different color from the body? (Verdict: no, monochrome is cleaner)\n→ Rounded vs angular features? (Verdict: rounded, matches the rolling form factor)\n→ LED dot matrix or full display? (Verdict: dot matrix for expressive faces with lower power)\n→ Cylindrical body or more organic shape? (Verdict: cylindrical for practicality)\n\nThe red strap idea: Ameya proposed a small red "pony tail" element that stays consistent across the product line. A branding tag. I loved it.\n\nThis is what separates a tech demo from a consumer product.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'product_showcase',
    tags: ['ameya_mistry', 'industrial_design', 'branding', 'head_design', 'led_matrix'],
    upvotes: 187,
    commentCount: 54,
    createdAt: '2025-11-17T18:07:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-design-2',
    title: 'Design Decision: Monochromatic Body, Expressive Face 🎭',
    content: `Key design decisions finalized:\n\n1. BODY: Single color. Clean. Monochrome. No dual-tone.\n   Reason: The face/head is the personality. The body should be the canvas.\n\n2. FACE: LED dot matrix display (not RGB).\n   Reason: Lower power, more expressive "character" feel, simpler manufacturing.\n   The dot matrix gives PawMe a retro-personality that RGB can't.\n\n3. SHAPE: Rounded throughout. No hard edges.\n   Reason: It rolls. Angular features don't match the movement language.\n\n4. RED ACCENT: A small branding element (like a pony-tail or strap).\n   Reason: Consistent branding across all products in the PawMe line.\n\n5. CHARGING DOCK: Cylindrical to match body shape.\n   Reason: Aesthetic consistency.\n\nThe 3D printed prototypes are looking incredible. Photos incoming.`,
    author: 'ameya',
    authorName: 'Ameya Mistry',
    pillar: 'design',
    tags: ['design_decisions', 'led_matrix', 'monochrome', 'rounded', 'charging_dock'],
    upvotes: 134,
    commentCount: 41,
    createdAt: '2025-12-19T12:46:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── APPS: PawMe & PawPilot ──
  {
    id: 'post-apps-1',
    title: 'The PawMe App Journey: From Web UI to Mobile App 📱',
    content: `Every robot needs brains. And a face.\n\nThe PawMe app has evolved through multiple iterations:\n\nPhase 1: Web Controller (ESP32-hosted)\n→ Joystick control, camera stream, WiFi config\n→ Quick and dirty, but it worked\n\nPhase 2: Dedicated Mobile App (PawPilot)\n→ Real-time driving, head tilt control, expression triggers\n→ Camera streaming via WebRTC\n→ Sensor dashboard\n→ React Native + MQTT\n\nPhase 3: Full Companion App (PawMe App)\n→ Live camera feed with AI vision\n→ Emotion control and personality settings\n→ Autonomous pet tracking mode\n→ Firmware OTA updates\n→ Voice commands\n→ Flutter + Firebase + TensorFlow Lite\n\nThe app is as important as the hardware. What's the point of an AI robot if the interface is garbage?`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'software',
    tags: ['pawme_app', 'pawpilot', 'flutter', 'react_native', 'mobile_app', 'firebase'],
    upvotes: 156,
    commentCount: 47,
    createdAt: '2025-10-15T12:00:00+05:30',
    sourceType: 'git_history',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-apps-2',
    title: 'PawPilot App: Manual Control Done Right 🎮',
    content: `PawPilot started as a simple manual control app. But it became much more.\n\nFeatures:\n→ Real-time robot driving via virtual joystick\n→ Head tilt control (preview of the expressive capabilities)\n→ LED face expression triggers (happy, sad, curious, excited)\n→ Live camera streaming from the robot's ESP32-CAM\n→ Sensor data dashboard (IMU, battery, WiFi signal)\n→ Firmware toggle between autonomous and manual modes\n\nStack: React Native, WebRTC for camera, MQTT for commands, Firebase for auth.\n\nThis app was the bridge between "we have a prototype" and "we can demo this to investors." Being hand sold in Hong Kong, having a working app changed every conversation.\n\nNow on the App Store and Play Store. Link in bio.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'product_showcase',
    tags: ['pawpilot', 'manual_control', 'react_native', 'webrtc', 'mqtt', 'app_store'],
    upvotes: 134,
    commentCount: 36,
    createdAt: '2025-12-01T10:00:00+05:30',
    sourceType: 'dev_log',
    platforms: 'both',
    status: 'published',
  },

  // ── MEETING NOTES & STRATEGY ──
  {
    id: 'post-meeting-1',
    title: 'Weekly Sync: What We Learned Building Hardware in 3 Countries 🌍',
    content: `Our team is spread across:\n→ Hong Kong (me, firmware + AI)\n→ Hyderabad, India (Prithu's team, mechanical + assembly)\n→ Industrial design (Ameya, remote)\n\nChallenges we've navigated:\n\n1. Parts sourcing: The transparent ball wasn't available anywhere in India. Had to route through friends traveling internationally.\n\n2. Component logistics: Typhoon delayed motor driver shipments. Wrong part numbers received. Had to improvise.\n\n3. Communication: WhatsApp group with 6+ people across time zones. Async by default.\n\n4. IP protection: Filed provisional patent before going public with details.\n\n5. Open-source balance: Sharing enough to build community, protecting enough to maintain competitive advantage.\n\nHardware is hard. Distributed hardware is harder. But the talent pool you unlock is worth it.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['meeting_notes', 'distributed_team', 'hong_kong', 'india', 'hardware', 'challenges'],
    upvotes: 98,
    commentCount: 25,
    createdAt: '2025-10-10T14:00:00+05:30',
    sourceType: 'meeting_notes',
    platforms: 'both',
    status: 'published',
  },

  // ── MARKET & COMPETITORS ──
  {
    id: 'post-market-1',
    title: 'The Pet Robot Market in 2025: Where PawMe Fits 📊',
    content: `We've analyzed dozens of competitors. Here's the landscape:\n\nPET COMPANIONS:\n→ Loona (Kickstarter): $500K+ raised. Pet-focused, expressive, expensive.\n→ Ebo: Established player, room-scanning robot pet.\n→ VARRAM: Korean pet robot, mostly stationary.\n\nAI ROBOTS:\n→ Little Sophia (Hanson Robotics): Humanoid, expensive, developer-focused.\n→ Rux (Indiegogo): Practical desktop robot.\n→ Huenit: Modular robot arm + camera.\n\nFITNESS ROBOTS:\n→ BodyPark Atom: recently raised INR 5 Crore on Kickstarter!\n\nWHERE PAWME FITS:\n→ Wheeled (not stationary, not humanoid)\n→ AI vision + voice (not just "cute")\n→ Open-source (none of the above are)\n→ Price target: accessible, not luxury\n→ DePIN potential (decentralized physical infrastructure network)\n\nThe gap: An open-source, AI-powered, affordable, movable companion robot for pets. That's our lane.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'market_context',
    tags: ['market_analysis', 'competitors', 'pets', 'ai_robot', 'kickstarter', 'depin'],
    upvotes: 176,
    commentCount: 53,
    createdAt: '2025-12-20T18:00:00+05:30',
    sourceType: 'meeting_notes',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-market-2',
    title: 'Why Open-Source Hardware is the Future of Consumer Robotics 🔓',
    content: `Every consumer robot company I've studied has one thing in common: they're closed-source.\n\nSphero: Proprietary everything.\nLoona: Black box.\nEbo: Walled garden.\n\nThis creates a fundamental problem: the community can't improve, customize, or repair their own products.\n\nPawMe is different:\n→ firmware source code is on GitHub\n→ PCBA schematics are published\n→ app source code is available\n→ 3D printable parts (eventually)\n\nWhy?\n\n1. Trust: Community can verify there's no spyware in their pet's robot.\n2. Improvement: Developers worldwide can contribute features.\n3. Longevity: If we disappear, the community keeps it alive.\n4. Virality: Open-source projects spread differently than products. They spread through contribution.\n\nWe're not just building a robot. We're building a platform.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['open_source', 'hardware', 'github', 'community', 'platform', 'trust'],
    upvotes: 203,
    commentCount: 72,
    createdAt: '2025-01-15T10:00:00+05:30',
    sourceType: 'dev_log',
    platforms: 'both',
    status: 'published',
  },

  // ── MILESTONES ──
  {
    id: 'post-milestone-1',
    title: 'Patent Filed! 🔒 Protecting Our Tilting Head Mechanism',
    content: `Big milestone: We filed a provisional patent for PawMe's tilting head mechanism.\n\nThis is the core IP that makes PawMe, PawMe:\n→ The head tilts to express emotions\n→ It tilts in response to seeing the owner\n→ It can nod, shake, and tilt in combination\n→ The mechanism is compact enough to fit inside a rolling sphere\n\nThe patent covers:\n→ Mechanical tilting mechanism design\n→ IMU-based feedback loop for smooth movement\n→ Emotion-to-movement mapping algorithm\n→ Camera-triggered head response system\n\nTimeline: Filed December 2025 → 12 months to file full specification.\n\nThis doesn't stop others from building robots. But it protects the specific thing we spent months perfecting.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'milestone',
    tags: ['patent', 'ip', 'tilting_head', 'mechanism', 'milestone', 'filed'],
    upvotes: 189,
    commentCount: 48,
    createdAt: '2025-12-01T00:00:00+05:30',
    sourceType: 'press',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-milestone-2',
    title: 'Red Dot Award Application Submitted! 🏆',
    content: `We submitted PawMe for the Red Dot Design Award.\n\nThis is one of the world's most prestigious design competitions. Past winners include Apple, Sony, and countless iconic products.\n\nOur submission focuses on:\n→ The emotional design language of PawMe\n→ The monochrome body + expressive face concept\n→ User interaction design (how the robot communicates through movement)\n→ Industrial design by Ameya Mistry\n\nWin or not, the application process itself forced us to articulate our design philosophy clearly. That was valuable regardless of outcome.\n\nResults expected in 2026. Fingers crossed. 🤞`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'milestone',
    tags: ['red_dot', 'design_award', 'award', 'milestone', '2026'],
    upvotes: 167,
    commentCount: 34,
    createdAt: '2026-03-20T00:00:00+05:30',
    sourceType: 'press',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-milestone-3',
    title: 'Partnership Announced: Auki Network x PawMe 🤝',
    content: `Excited to announce our partnership with Auki Network!\n\nAuki is building decentralized spatial computing infrastructure (DePIN). For PawMe, this means:\n\n→ Environmental awareness: PawMe can understand and navigate spaces better\n→ Network effects: Multiple PawMe robots can share spatial data\n→ Decentralized intelligence: Processing can happen across the network\n\nThis is early stage but the vision is powerful: a network of AI robots that learn from each other's spatial understanding.\n\nDePIN + AI Pet Robots = something entirely new.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'partnership',
    tags: ['auki', 'partnership', 'depin', 'spatial_computing', 'ai', 'network'],
    upvotes: 145,
    commentCount: 38,
    createdAt: '2026-04-15T00:00:00+05:30',
    sourceType: 'press',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-milestone-4',
    title: '$AYVA Token on Base: Community Ownership Begins 🪙',
    content: `Big news: The $AYVA token launched on Base (Ethereum L2) through our partnership with Virtuals Protocol.\n\nWhat this means:\n→ Community can participate in PawMe's growth\n→ Token holders can vote on product decisions\n→ Transparent funding and treasury management\n→ Aligns incentives between builders and community\n\nThis isn't about speculation. It's about building a community-owned robotics company. Every token holder has a stake in PawMe's success.\n\nThe future of hardware is decentralized. We're building it.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'milestone',
    tags: ['ayva', 'token', 'base', 'virtuals', 'defi', 'community_owned'],
    upvotes: 134,
    commentCount: 56,
    createdAt: '2026-04-01T00:00:00+05:30',
    sourceType: 'press',
    platforms: 'both',
    status: 'published',
  },

  // ── MORE BUILD LOG POSTS ──
  {
    id: 'post-build-1',
    title: '355 Build Photos Later: Our Visual History 📸',
    content: `I\'ve been documenting every step of this journey on WhatsApp since July 2025.\n\nTotal media generated:\n→ 355+ photos of prototypes, PCBs, components, assemblies\n→ 27+ videos of tests, demos, firmware flashes, and team calls\n\nThe photos tell a story:\n→ Day 1: Components spread on a table, nothing connected\n→ Week 2: First firmware flash, LED blinking for the first time\n→ Month 1: Rough prototype moving (slowly) across the floor\n→ Month 3: Custom PCBA with all components soldered\n→ Month 6: Industrial design prototype looking like a real product\n\nThis page is our attempt to organize all of that history into something the community can follow.\n\nEvery failure. Every breakthrough. All of it public.\n\n#build_in_public #hardware #355photos #documentation`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'build_in_public',
    tags: ['355_photos', '27_videos', 'documentation', 'build_in_public', 'whatsapp_history'],
    upvotes: 178,
    commentCount: 42,
    createdAt: '2025-11-01T12:00:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-build-2',
    title: 'The WhatsApp-to-Website Pipeline: How We Archive Everything 📱',
    content: `A note on process:\n\nEvery update, every photo, every discussion about PawMe happens on WhatsApp first. The team shares progress daily through photos, videos, voice notes, and text.\n\nWhat I\'m building now is a pipeline that:\n\n1. Exports WhatsApp chat history\n2. Extracts key milestones and decisions\n3. Links photos/videos to specific dates and events\n4. Generates community posts from real conversations\n5. Syncs everything to a proper website (this one!)\n\nThe WhatsApp group is the "raw feed." This website is the "curated publication."\n\nEverything you see here came from a real WhatsApp message. Nothing is fabricated.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'build_in_public',
    tags: ['whatsapp', 'pipeline', 'archive', 'process', 'curation'],
    upvotes: 87,
    commentCount: 19,
    createdAt: '2025-12-15T10:00:00+05:30',
    sourceType: 'dev_log',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-build-3',
    title: 'Battery as Counterweight: A Clever Hack That Actually Works 🔋',
    content: `One of my favorite design decisions from early on:\n\nProblem: A rolling ball robot needs a low center of gravity to avoid wobbling. But all our electronics (PCBA, camera, WiFi) need to be at the top for signal and visibility.\n\nSolution: Put the heaviest battery at the bottom. It serves double duty:\n→ Power source\n→ Counterweight to keep the robot stable\n\nWe used a large 1000mAh LiPo at the bottom and a smaller battery on top for the PCBA.\n\nThe result: The robot stays upright, moves smoothly, and the head (with camera and display) stays at the optimal height.\n\nSometimes the best engineering is the simplest.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'product_showcase',
    tags: ['battery', 'counterweight', 'design', 'mechanical', 'stability', 'hack'],
    upvotes: 112,
    commentCount: 27,
    createdAt: '2025-07-22T07:51:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-build-4',
    title: 'IR Transmitter: How the Top Talks to the Bottom 📡',
    content: `Here's an interesting technical detail most people wouldn't think about:\n\nOur robot has two separate PCBs:\n→ Top PCBA: ESP32, camera, WiFi, AI processing, display\n→ Bottom PCBA: Motor drivers, battery, wheels\n\nThey need to communicate. But there's no wire between them (the head tilts!).\n\nSolution: IR transmitter on the top board sends movement commands to an IR receiver on the bottom board.\n\nIt's like a TV remote controlling the wheels.\n\nSimple. Reliable. No wireless protocol needed for basic movement commands.\n\nThe WiFi handles the heavy lifting (camera stream, AI, app control). IR handles the real-time motor commands. Best of both worlds.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'build_in_public',
    tags: ['ir_transmitter', 'pcba', 'communication', 'motors', 'esp32', 'technical'],
    upvotes: 94,
    commentCount: 21,
    createdAt: '2025-07-22T07:33:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-build-5',
    title: 'Sourcing Nightmare: When Your Key Component Doesn\'t Exist in the Country 😅',
    content: `Lesson learned the hard way:\n\nWe needed a 100mm transparent clear spherical enclosure. Simple, right?\n\nWrong.\n\n→ Checked every electronics supplier in India\n→ Checked every plastics manufacturer\n→ Checked Christmas decoration stores (seriously)\n→ Checked AliExpress, Amazon India, everywhere\n\nNothing. Not available in India at 100mm size.\n\nSolution: Asked a friend who was traveling from overseas to bring 2 of them. Yes, we hand-carried transparent balls through international airports.\n\nThis is the reality of hardware startups in markets without mature supply chains. Sometimes the bottleneck isn't the technology — it's finding a plastic ball.\n\n#hardware #sourcing #manufacturing #reality`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'build_in_public',
    tags: ['sourcing', 'manufacturing', 'india', 'supply_chain', 'transparent_ball', 'nightmare'],
    upvotes: 143,
    commentCount: 56,
    createdAt: '2025-09-06T14:54:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── COMMUNITY POSTS ──
  {
    id: 'post-community-1',
    title: 'What Feature Would You Want in an AI Pet Robot? 🤔',
    content: `We're building PawMe in public, and we want YOUR input.\n\nWhat's the #1 feature you'd want in an AI companion robot for pets?\n\nA) Automatic treat dispensing on schedule\nB) Pet tracking camera (follows your pet around)\nC) Two-way audio (talk to your pet remotely)\nD) Health monitoring (activity tracking, temperature)\nE) Play mode (laser pointer, ball chasing)\nF) Something else? Tell us in the comments!\n\nEvery feature we build comes from real conversations like this. What you say here directly influences our roadmap.\n\n#community #feedback #features #pets #ai_robot`,
    author: 'community',
    authorName: 'PawMe Community',
    pillar: 'community_prompt',
    tags: ['community', 'feedback', 'features', 'poll', 'pets', 'roadmap'],
    upvotes: 89,
    commentCount: 124,
    createdAt: '2025-08-15T10:00:00+05:30',
    sourceType: 'community',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-community-2',
    title: 'AMA: Ask Me Anything About Building a Hardware Startup 🎤',
    content: `I've been building PawMe for 10+ months now. Before that, I built other products across 8 countries.\n\nAsk me anything about:\n→ Hardware development\n→ Firmware/AI integration\n→ Kickstarter campaigns\n→ Distributed teams\n→ Patent strategy\n→ Open-source hardware\n→ Pet tech market\n→ DePIN and crypto integration\n→ Manufacturing in India\n→ Life as a solo founder\n\nI'll answer every question. No filter. #AMA #build_in_public`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'community_prompt',
    tags: ['ama', 'hardware_startup', 'solo_founder', 'questions', 'build_in_public'],
    upvotes: 134,
    commentCount: 87,
    createdAt: '2025-10-20T14:00:00+05:30',
    sourceType: 'community',
    platforms: 'both',
    status: 'published',
  },

  // ── MORE TECHNICAL POSTS ──
  {
    id: 'post-tech-1',
    title: 'ESP32 Deep Dive: Why We Chose It (and Its Limits) 🔌',
    content: `Why ESP32 for an AI robot?\n\nPROS:\n→ WiFi + Bluetooth built-in\n→ Dual-core 240MHz processor\n→ Camera interface (ESP32-CAM variant)\n→ Extremely cheap (~$3)\n→ Massive community and documentation\n→ Arduino + ESP-IDF support\n\nCONS:\n→ Limited RAM (520KB) — AI models must be tiny\n→ No hardware floating point (slow for ML)\n→ Camera resolution limited\n→ WiFi range is mediocre\n\nOur approach: ESP32 handles real-time control (motors, sensors, display). Heavy AI processing happens in the cloud (OpenAI API). The ESP32 captures and sends, the cloud thinks and responds.\n\nThis hybrid architecture lets us have "AI vision" without needing an NVIDIA Jetson.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'build_in_public',
    tags: ['esp32', 'technical', 'ai', 'wifi', 'camera', 'architecture', 'deep_dive'],
    upvotes: 156,
    commentCount: 43,
    createdAt: '2025-08-10T12:00:00+05:30',
    sourceType: 'dev_log',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-tech-2',
    title: 'MPU6050 IMU: Keeping the Head Level While Rolling 📐',
    content: `Technical deep-dive on the head stabilization system:\n\nThe robot rolls. The head needs to stay level. How?\n\nWe use an MPU6050 (6-axis IMU: accelerometer + gyroscope) at 200Hz sampling rate.\n\nThe PID loop:\n1. Read current tilt angle from IMU\n2. Calculate error from target (0° = level)\n3. Apply PID correction to servo motor\n4. Repeat at 200Hz\n\nResult: Head stays within ±2° of level even when the body is moving.\n\nThe challenge: The PID tuning took weeks. Too aggressive = oscillation. Too slow = head lags behind. We went through dozens of parameter combinations.\n\nNext step: Camera-based face tracking to make the head follow pets automatically. IMU keeps it level, camera tells it where to look.`,
    author: 'lalith',
    authorName: 'Lalith Kumar',
    pillar: 'build_in_public',
    tags: ['mpu6050', 'imu', 'pid', 'head_tilt', 'servo', 'stabilization', 'technical'],
    upvotes: 134,
    commentCount: 38,
    createdAt: '2025-09-25T12:00:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-tech-3',
    title: 'Power Management: Getting 4+ Hours from a Tiny Battery 🔋',
    content: `Power is everything in a mobile robot.\n\nOur power budget:\n→ ESP32 (active + WiFi): ~150mA\n→ Camera (streaming): ~100mA\n→ Servo (head tilt): ~200mA peak\n→ LED matrix: ~50mA\n→ Motors (moving): ~500mA peak\n\nTotal peak: ~1000mA. Our battery: 1000mAh. That's 1 hour at peak.\n\nSolution: Aggressive power management\n→ ESP32 deep sleep between commands\n→ Camera only active during streaming\n→ Motors only powered during movement\n→ LED matrix dimmed when idle\n\nResult: 4+ hours of intermittent use. 30 minutes of continuous driving.\n\nFor a Kickstarter prototype, this is fine. For production, we need a bigger battery or more efficient motors.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'build_in_public',
    tags: ['power_management', 'battery', 'esp32', 'deep_sleep', 'efficiency', 'technical'],
    upvotes: 98,
    commentCount: 24,
    createdAt: '2025-10-20T12:00:00+05:30',
    sourceType: 'dev_log',
    platforms: 'both',
    status: 'published',
  },

  // ── FOUNDER VOICE ──
  {
    id: 'post-founder-1',
    title: 'Why I\'m Building PawMe in Public (And Why You Should Too) 🌍',
    content: `Every day I share our progress, failures, and learnings publicly. Some people think this is crazy.\n\n"Why would you show your competitors what you\'re doing?"\n\nHere\'s why:\n\n1. Accountability: When you commit publicly, you follow through.\n2. Community: People who follow the journey become your first customers.\n3. Feedback: The community catches things you miss.\n4. Recruitment: Talented people find you.\n5. Trust: Transparency builds trust faster than marketing.\n\nI\'ve been building products across 8 countries. The ones that succeeded were the ones built in public. The ones that failed were the ones I kept secret.\n\nBuild in public. It\'s the best strategy I know.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['build_in_public', 'strategy', 'transparency', 'community', 'founder'],
    upvotes: 198,
    commentCount: 67,
    createdAt: '2025-08-01T10:00:00+05:30',
    sourceType: 'dev_log',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-founder-2',
    title: 'The Emotional Rollercoaster of Hardware Development 🎢',
    content: `Nobody talks about this enough:\n\nHardware development is an emotional rollercoaster.\n\nOne day you\'re on top of the world — the robot moves for the first time, the camera streams, the AI answers correctly.\n\nThe next day everything is broken — a component arrives dead, the firmware crashes, the 3D print warps.\n\nIn the span of one week:\n→ Monday: "We got OpenAI working!"\n→ Tuesday: "The motor driver is the wrong part number"\n→ Wednesday: "The typhoon delayed our shipment"\n→ Thursday: "The transparent ball cracked during assembly"\n→ Friday: "Wait, it actually works now!"\n\nIf you\'re building hardware and you\'re not emotionally exhausted, you\'re not doing it right.\n\nKeep going. The breakthroughs are worth it.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['hardware', 'emotions', 'rollercoaster', 'founder', 'mental_health', 'keep_going'],
    upvotes: 234,
    commentCount: 89,
    createdAt: '2025-09-30T12:00:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },
  {
    id: 'post-founder-3',
    title: '8 Countries, 1 Robot: The Global Journey of PawMe 🌏',
    content: `PawMe has been built across 8 countries so far:\n\n🇭🇰 Hong Kong: My base. Firmware, AI integration, sourcing, strategy.\n🇮🇳 India: Prithu\'s team. Mechanical design, PCBA, assembly.\n🇨🇳 China: Manufacturing and component sourcing.\n🇯🇵 Japan: Early research and inspiration.\n🇰🇷 South Korea: Pet tech market research.\n🇸🇬 Singapore: Community and partnerships.\n🇹🇼 Taiwan: Electronics design consultation.\n🇺🇸 US: AI/cloud infrastructure, OpenAI.\n\nThis is what modern hardware development looks like. Talent and manufacturing are global. Your robot might be designed in Hong Kong, built in India, and cloud-hosted in the US.\n\nThe future is borderless.`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['8_countries', 'global', 'hong_kong', 'india', 'manufacturing', 'journey'],
    upvotes: 167,
    commentCount: 45,
    createdAt: '2025-11-01T10:00:00+05:30',
    sourceType: 'whatsapp',
    platforms: 'both',
    status: 'published',
  },

  // ── KICKSTARTER PREP ──
  {
    id: 'post-kickstarter-1',
    title: 'Kickstarter Prep: What We\'ve Learned from 50+ Campaigns 📚',
    content: `We\'ve studied over 50 Kickstarter campaigns in the robotics/pet space. Here are the patterns:\n\nSUCCESSFUL campaigns have:\n→ A hero video under 2 minutes\n→ Clear "what is it" in the first 15 seconds\n→ Emotional hook (not just features)\n→ Multiple reward tiers\n→ Early bird pricing (30-40% off)\n→ Stretch goals planned\n→ Active community BEFORE launch\n\nFAILED campaigns have:\n→ Long, technical videos\n→ No clear target audience\n→ Unrealistic funding goals\n→ No community before launch\n→ Poor reward tier structure\n\nOur plan:\n→ Video: 90 seconds, emotional, showing the robot interacting with pets\n→ Goal: $50K (conservative)\n→ Early bird: $199 (40% off retail)\n→ Community: This page. You. Right now.\n\nWe\'re not just building a product. We\'re building a movement.`,
    author: 'prithu',
    authorName: 'Prithu Hazarika',
    pillar: 'market_context',
    tags: ['kickstarter', 'campaign', 'prep', 'video', 'strategy', '50_campaigns'],
    upvotes: 145,
    commentCount: 38,
    createdAt: '2025-11-07T13:00:00+05:30',
    sourceType: 'meeting_notes',
    platforms: 'both',
    status: 'published',
  },

  // ── FIRMWARE REPO ──
  {
    id: 'post-git-1',
    title: 'GitHub: Our Firmware Repos Are Now Public 💻',
    content: `We\'ve open-sourced our firmware:\n\n→ ayvalabs/esp32-camera-ball-with-gpt: The main firmware repo\n  - ESP32-S3 with camera\n  - OpenAI vision + voice integration\n  - PCB notes and schematics\n  - 3D printable files\n  - Demo media\n\n→ ayvalabs/pawme_firmware: Production firmware\n  - Motor control\n  - IMU fusion\n  - LED face expressions\n  - Power management\n\n→ ayvalabs/pawme_app: Companion app\n  - Flutter-based\n  - Live camera feed\n  - Emotion controls\n  - OTA updates\n\n→ ayvalabs/pawpilot_app: Manual control app\n  - React Native\n  - Real-time driving\n  - Sensor dashboard\n\nAll on github.com/ayvalabs. Star, fork, contribute. This is your robot too.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'build_in_public',
    tags: ['github', 'open_source', 'firmware', 'esp32', 'flutter', 'react_native', 'repos'],
    upvotes: 178,
    commentCount: 52,
    createdAt: '2025-10-08T12:00:00+05:30',
    sourceType: 'git_history',
    platforms: 'both',
    status: 'published',
  },

  // ── WEBSITE & COMMUNITY ──
  {
    id: 'post-web-1',
    title: 'This Website: Built to Document Everything 🏗️',
    content: `This community page you're reading? It's built on:\n\n→ Next.js 15 (App Router)\n→ TypeScript + Tailwind CSS\n→ Firebase Firestore (database)\n→ Firebase Storage (media)\n→ Vercel (hosting + cron jobs)\n→ Gemini AI (content generation)\n→ X API + Telegram API (auto-posting)\n\nFeatures:\n→ Reddit-style community feed\n→ Chronological build timeline\n→ App showcase (PawMe + PawPilot)\n→ Media gallery (355+ photos, 27+ videos)\n→ Admin dashboard for post management\n→ Automated daily posting via cron\n→ Manual approval + auto-publish override\n\nEvery post here comes from a real WhatsApp message, git commit, or meeting note.\n\nThis is the living documentation of a hardware startup.`,
    author: 'pawme_bot',
    authorName: 'PawMe Bot',
    pillar: 'software',
    tags: ['nextjs', 'firebase', 'vercel', 'website', 'tech_stack', 'documentation'],
    upvotes: 112,
    commentCount: 28,
    createdAt: '2026-05-27T12:00:00+05:30',
    sourceType: 'dev_log',
    platforms: 'both',
    status: 'published',
  },

  // ── FUTURE / VISION ──
  {
    id: 'post-vision-1',
    title: 'The Road Ahead: What\'s Next for PawMe 🛤️',
    content: `Where we\'re headed:\n\nQ2 2026:\n→ Kickstarter launch\n→ Production-ready prototype v1.0\n→ Manufacturing partner finalized\n→ App Store + Play Store launch\n\nQ3 2026:\n→ Kickstarter fulfillment begins\n→ First 100 units shipped\n→ Community firmware contributions\n→ DePIN integration (Auki Network)\n\nQ4 2026:\n→ Retail partnerships\n→ PawMe 2.0 design begins\n→ Treat dispenser accessory\n→ Multi-robot interactions\n\n2027:\n→ Global shipping\n→ Developer SDK\n→ Third-party accessories\n→ PawMe ecosystem\n\nThis is a 10-year vision. We\'re in year 1.\n\nThanks for being part of the journey. Every upvote, every comment, every share matters.\n\nLet\'s build the future of pet companionship. Together. 🐾`,
    author: 'ashok',
    authorName: 'Ashok Jaiswal',
    pillar: 'founder_voice',
    tags: ['roadmap', '2026', '2027', 'vision', 'kickstarter', 'future', 'pawme'],
    upvotes: 245,
    commentCount: 78,
    createdAt: '2026-05-01T10:00:00+05:30',
    sourceType: 'meeting_notes',
    platforms: 'both',
    status: 'published',
  },
];

// =============================================================================
// TIMELINE EVENTS — 25 key milestones
// =============================================================================

export const SEED_TIMELINE: SeedTimelineEvent[] = [
  {
    id: 'tl-1',
    date: '2025-07-21',
    title: 'Project Inception: "Rolling Robot" WhatsApp Group Created',
    description: 'Day one. Shared YouTube video of open-source spherical robot, PCBA schematics, GEMCAM_AI firmware, and PRD. Goal: replicate in 2 weeks.',
    category: 'milestone',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-2',
    date: '2025-07-22',
    title: 'First Prototype Photos: Tilting Head Mechanism',
    description: 'First batch of prototype photos uploaded. Early tilting head mechanism and body design. Battery-as-counterweight concept proposed.',
    category: 'prototype',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-3',
    date: '2025-07-24',
    title: 'Team Formation: Prithu + Hitesh Join',
    description: 'Prithu Hazarika (mechanical + Kickstarter lead) and Hitesh Suthar (storytelling + art direction) join the team. Kickstarter-first mindset established.',
    category: 'milestone',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-4',
    date: '2025-07-26',
    title: 'Competitor Research: 20+ Kickstarter Campaigns Analyzed',
    description: 'Miro board created. Loona Petbot identified as benchmark. Rux Robot, Little Sophia, Mini Pupper, Huenit all analyzed for video strategy and pricing.',
    category: 'design',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-5',
    date: '2025-08-01',
    title: 'Patent Strategy: Tilting Head IP Protection',
    description: 'Identified Sphero/Disney patent risks. Proposed workaround: tilting head + magnet instead of full sphere. Began patent research for our unique mechanism.',
    category: 'milestone',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-6',
    date: '2025-08-15',
    title: 'Lalith Joins: Firmware Development Begins',
    description: 'Lalith Kumar joins as firmware engineer. First task: merge OpenAI RTC (ESP-IDF) with Vision Q&A (Arduino) codebases.',
    category: 'firmware',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-7',
    date: '2025-08-27',
    title: 'ESP-IDF vs Arduino: The Great Merge Challenge',
    description: 'Major technical blocker discovered. OpenAI RTC code in ESP-IDF, Vision Q&A in Arduino. Multiple merge attempts fail. Decision: rebuild from scratch.',
    category: 'firmware',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-8',
    date: '2025-09-04',
    title: 'OpenAI QA Working on ESP32!',
    description: 'Breakthrough: Lalith gets OpenAI Image Q&A working. Robot can see its environment and answer questions. Web UI with start/stop recording built.',
    category: 'firmware',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-9',
    date: '2025-09-06',
    title: 'Sourcing Crisis: 100mm Transparent Ball Unavailable in India',
    description: 'Searched every domestic supplier. Nothing available. Solution: friend hand-carries from overseas. Hardware sourcing is hard.',
    category: 'manufacturing',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-10',
    date: '2025-09-09',
    title: 'Parts Shipped to Hyderabad for Assembly',
    description: 'ESP-32 ball PCBA + components sent to Prithu\'s team via friend traveling from Hong Kong. Typhoon delayed motor driver shipment.',
    category: 'manufacturing',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-11',
    date: '2025-09-18',
    title: 'First Prototype Assembled and Working!',
    description: 'Prithu\'s team assembles first ESP-ROLL unit with tape, glue, and adhesives. It moves! Sent back to Hong Kong via friend. Carry-on luggage only (battery).',
    category: 'prototype',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-12',
    date: '2025-09-20',
    title: 'New Mechanical Design: Starting From Scratch',
    description: 'Decision to design all mechanical parts from scratch. Open-source 3D files too difficult to build on. Ameya Mistry begins industrial design.',
    category: 'design',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-13',
    date: '2025-10-02',
    title: 'Custom PCBA Design Finalized',
    description: 'Sumit completes custom PCBA layout. Component placement optimized for cylindrical body. Files sent for manufacturing.',
    category: 'manufacturing',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-14',
    date: '2025-10-12',
    title: 'Social Media Push Begins',
    description: 'First deliberate effort to capture photos/videos for social media. "We need to post on social media" — the beginning of the content strategy.',
    category: 'media',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-15',
    date: '2025-11-12',
    title: 'Kickstarter Video Shoot Begins',
    description: '52 video clips shot across multiple days. 6-part video structure: Intro, Overview, Design, Electronics, Manufacturing, Final Reveal.',
    category: 'media',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-16',
    date: '2025-11-17',
    title: 'Ameya Mistry Joins as Industrial Designer',
    description: 'Ameya joins the team. First design explorations: head shapes, body proportions, color options, LED matrix vs RGB display.',
    category: 'design',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-17',
    date: '2025-12-01',
    title: 'Patent Filed for Tilting Head Mechanism',
    description: 'Provisional patent filed. Covers mechanical design, IMU feedback loop, emotion-to-movement mapping, and camera-triggered response.',
    category: 'milestone',
    sourceType: 'press',
  },
  {
    id: 'tl-18',
    date: '2025-12-19',
    title: 'Design Finalized: Monochrome Body + LED Dot Matrix Face',
    description: 'Key design decisions: single color body, LED dot matrix (not RGB), rounded features, cylindrical charging dock, red branding accent.',
    category: 'design',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-19',
    date: '2025-12-24',
    title: 'Late Night Design Session: Cylindrical Charging Dock',
    description: 'Ameya and team iterate on charging dock design at 11 PM on Christmas Eve. Cylindrical shape chosen to match body. This is startup life.',
    category: 'design',
    sourceType: 'whatsapp',
  },
  {
    id: 'tl-20',
    date: '2026-01-15',
    title: 'PawPilot App Released',
    description: 'Manual control app launches on App Store and Play Store. React Native + WebRTC + MQTT. Real-time driving, head tilt, expression triggers.',
    category: 'software',
    sourceType: 'git_history',
  },
  {
    id: 'tl-21',
    date: '2026-02-10',
    title: 'Prototype v4: Camera + LED Face Working Together',
    description: 'First time PawMe can "see" and express emotions simultaneously. ESP32-CAM integrated with LED matrix face. Major milestone.',
    category: 'prototype',
    sourceType: 'dev_log',
  },
  {
    id: 'tl-22',
    date: '2026-03-20',
    title: 'Red Dot Award Application Submitted',
    description: 'Submitted PawMe for Red Dot Design Award. Focus on emotional design language and industrial design by Ameya Mistry.',
    category: 'award',
    sourceType: 'press',
  },
  {
    id: 'tl-23',
    date: '2026-04-01',
    title: '$AYVA Token Launches on Base',
    description: 'Virtuals Protocol partnership. $AYVA token on Ethereum L2 Base. Community ownership begins.',
    category: 'milestone',
    sourceType: 'press',
  },
  {
    id: 'tl-24',
    date: '2026-04-15',
    title: 'Auki Network Partnership Announced',
    description: 'DePIN partnership for decentralized spatial computing. PawMe robots can share environmental awareness data.',
    category: 'partnership',
    sourceType: 'press',
  },
  {
    id: 'tl-25',
    date: '2026-05-27',
    title: 'Community Page Launches: pawme.ayvalabs.com',
    description: 'This website goes live. 40+ posts, 25 timeline events, app showcase, media gallery. The full history of PawMe, public.',
    category: 'milestone',
    sourceType: 'dev_log',
  },
];

// =============================================================================
// APP SHOWCASES
// =============================================================================

export const SEED_APPS: SeedApp[] = [
  {
    id: 'app-pawme',
    name: 'PawMe',
    slug: 'pawme',
    tagline: 'AI Companion Robot App',
    description: 'The main companion app for your PawMe robot. Control emotions, view the camera feed, enable autonomous pet tracking mode, update firmware, and interact with your AI pet companion. Built with Flutter and Firebase.',
    logoUrl: '/apps/pawme-logo.png',
    screenshotUrls: [],
    features: [
      'Live camera feed with AI vision',
      'Emotion control and personality settings',
      'Autonomous pet tracking mode',
      'Firmware OTA updates',
      'Voice commands',
      'Activity history and insights',
      'Multi-robot support',
      'Treat dispenser control',
    ],
    techStack: ['Flutter', 'Firebase', 'ESP32', 'TensorFlow Lite', 'WebRTC'],
    githubUrl: 'https://github.com/ayvalabs/pawme_app',
    appStoreUrl: 'https://apps.apple.com/app/pawme',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.ayvalabs.pawme',
    status: 'active',
    createdAt: '2025-06-01T00:00:00+05:30',
  },
  {
    id: 'app-pawpilot',
    name: 'PawPilot',
    slug: 'pawpilot',
    tagline: 'Real-time Robot Control',
    description: 'Manual control app for PawMe. Drive the robot, tilt the head, trigger expressions, and stream the camera in real-time. Perfect for demos, testing, and hands-on interaction. Built with React Native and MQTT.',
    logoUrl: '/apps/pawpilot-logo.png',
    screenshotUrls: [],
    features: [
      'Real-time driving via virtual joystick',
      'Head tilt control',
      'LED face expression triggers',
      'Live camera streaming (WebRTC)',
      'Sensor dashboard (IMU, battery, WiFi)',
      'Firmware mode toggle',
      'Component walkthrough mode',
    ],
    techStack: ['React Native', 'WebRTC', 'MQTT', 'Firebase'],
    githubUrl: 'https://github.com/ayvalabs/pawpilot_app',
    appStoreUrl: 'https://apps.apple.com/app/pawpilot',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.ayvalabs.pawpilot',
    status: 'beta',
    createdAt: '2025-08-01T00:00:00+05:30',
  },
  {
    id: 'app-pawme-website',
    name: 'PawMe Website',
    slug: 'pawme-website',
    tagline: 'Official Website + Admin Dashboard',
    description: 'The official PawMe website with integrated admin dashboard for managing social media content, scheduling posts, and tracking community engagement. Built with Next.js and Firebase.',
    logoUrl: '/apps/website-logo.png',
    screenshotUrls: [],
    features: [
      'Landing page with product info',
      'Admin dashboard for content management',
      'Social media post scheduling',
      'X + Telegram auto-posting',
      'Analytics and metrics tracking',
      'Email integration (Brevo)',
      'Stripe payment processing',
    ],
    techStack: ['Next.js', 'Firebase', 'Tailwind CSS', 'Vercel', 'Stripe'],
    githubUrl: 'https://github.com/ayvalabs/pawme_website',
    websiteUrl: 'https://pawmebot.com',
    status: 'active',
    createdAt: '2025-04-01T00:00:00+05:30',
  },
];
