/**
 * PawMeBot Community — Day-by-Day Timeline Generator
 * 
 * Parses the WhatsApp chat export and creates a chronological timeline
 * with actual dates, media references, and conversation summaries.
 * 
 * This is a build-time script that generates the timeline data structure.
 * Run with: npx tsx src/lib/generate-timeline.ts
 */

export interface DayEvent {
  dayNumber: number;        // Day 0, Day 1, Day 2, ...
  date: string;             // YYYY-MM-DD
  dateLabel: string;        // "July 21, 2025"
  title: string;
  summary: string;
  mediaFiles: string[];     // Attached files from this day
    mediaTypes: ('image' | 'video' | 'document')[];
  participants: string[];
  messageCount: number;
  pillar: 'build_in_public' | 'product_showcase' | 'founder_voice' | 'community_prompt' | 'market_context' | 'design' | 'media' | 'software' | 'milestone' | 'partnership' | 'manufacturing' | 'prototype' | 'firmware';
  tags: string[];
  sourceType: 'whatsapp';
}

// =============================================================================
// EXTRACTED FROM WHATSAPP CHAT — Day 0 = July 21, 2025
// =============================================================================

export const TIMELINE_DAYS: DayEvent[] = [
  {
    dayNumber: 0,
    date: '2025-07-21',
    dateLabel: 'July 21, 2025',
    title: 'Day 0: Project Inception — "Rolling Robot" is Born',
    summary: `Ashok creates the "Rolling Robot - Pawme" WhatsApp group. Within the first hour, he shares a YouTube video of an open-source spherical rolling robot, PCBA schematics, the GEMCAM_AI firmware source code from GitHub, and a Perplexity research link. The Product Requirements Document (PRD) is created on Google Docs. The goal is audacious: replicate the mechanical rolling robot design in just 2 weeks, then layer on AI vision, voice Q&A, and emotional intelligence. Prithu Hazarika confirms it can be built and schedules a call for the same day. The team discusses the 2-week timeline to replicate the first prototype.`,
    mediaFiles: ['00000013-PHOTO-2025-07-21-17-51-47.jpg'],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Sumit Dandekar'],
    messageCount: 17,
    pillar: 'founder_voice',
    tags: ['day_0', 'origin', 'kickoff', 'prd', 'youtube', 'schematics', 'firmware'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 1,
    date: '2025-07-22',
    dateLabel: 'July 22, 2025',
    title: 'Day 1: First Prototype Photos + Battery Strategy',
    summary: `First batch of prototype photos uploaded — 12 images showing early tilting head mechanism and body design from multiple angles. Ashok proposes the battery-as-counterweight concept: a large heavy battery at the bottom for stability and a small battery on top for the PCBA. The top PCBA uses WiFi/AI for movement commands, with an IR transmitter sending commands to the bottom wheel assembly. This is designed to avoid Sphero/Disney patents. Ashok also shares the GEMCAM_AI Arduino code for connecting Gemini AI to the camera. The team begins discussing how to make the head tilt with servo + IMU feedback.`,
    mediaFiles: [
      '00000017-PHOTO-2025-07-22-07-20-53.jpg',
      '00000018-PHOTO-2025-07-22-07-20-53.jpg',
      '00000019-PHOTO-2025-07-22-07-20-54.jpg',
      '00000020-PHOTO-2025-07-22-07-20-54.jpg',
      '00000021-PHOTO-2025-07-22-07-20-54.jpg',
      '00000022-PHOTO-2025-07-22-07-20-54.jpg',
      '00000023-PHOTO-2025-07-22-07-20-54.jpg',
      '00000024-PHOTO-2025-07-22-07-20-54.jpg',
      '00000025-PHOTO-2025-07-22-07-20-55.jpg',
      '00000026-PHOTO-2025-07-22-07-20-55.jpg',
      '00000027-PHOTO-2025-07-22-07-20-55.jpg',
      '00000028-PHOTO-2025-07-22-07-20-55.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Sumit Dandekar'],
    messageCount: 20,
    pillar: 'product_showcase',
    tags: ['prototype', 'photos', 'battery', 'counterweight', 'ir_transmitter', 'patent_avoidance'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 3,
    date: '2025-07-24',
    dateLabel: 'July 24, 2025',
    title: 'Day 3: Team Forming + Kickstarter-First Strategy',
    summary: `Prithu adds Hitesh Suthar to the group — a talented product designer for storytelling and art direction. Discovery: the Disney/Sphero patent situation is confirmed. The team pivots to a magnet-based head attachment to work around IP. Ashok shares a product demo video showing the desired feature set: camera, mic, speaker, laser pointer, wireless charger. The reference Kickstarter campaign is shared (Loona Petbot) as the benchmark for video quality. Prithu creates a Miro board for visual research and storyboarding. Hitesh confirms the team can make a snappy Kickstarter video using their network. The group icon and description are updated multiple times as the vision crystallizes.`,
    mediaFiles: [
      '00000040-VIDEO-2025-07-24-13-24-18.mp4',
      '00000049-PHOTO-2025-07-24-19-20-21.jpg',
    ],
    mediaTypes: ['video', 'image'],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Hitesh Suthar', 'Sumit Dandekar'],
    messageCount: 18,
    pillar: 'founder_voice',
    tags: ['team', 'hitesh', 'kickstarter', 'miro', 'patent', 'strategy', 'loona'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 5,
    date: '2025-07-26',
    dateLabel: 'July 26, 2025',
    title: 'Day 5: Competitor Research — 20+ Campaigns Analyzed',
    summary: `Ashok shares an extensive list of competitor and reference campaigns: Loona Petbot, Rux Robot (Indiegogo), Little Sophia (Hanson Robotics), Mini Pupper (open-source robot dog), Huenit AI robot arm, and several others. The team analyzes what makes each campaign successful. Focus areas: video structure, emotional hook, pricing tiers, and community building. Hitesh and Prithu confirm they've discussed the storytelling approach. The Miro board is actively being used for research. The industrial design direction begins to take shape — rounded forms, expressive face, clean aesthetics.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Hitesh Suthar'],
    messageCount: 10,
    pillar: 'market_context',
    tags: ['competitor_research', 'kickstarter', 'indiegogo', 'analysis', 'miro'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 15,
    date: '2025-08-05',
    dateLabel: 'August 5, 2025',
    title: 'Day 15: Firmware Development Begins — The ESP-IDF Challenge',
    summary: `Lalith Kumar joins the firmware development effort. The team begins working on merging two incompatible codebases: OpenAI RTC (Real-Time Communication) written in ESP-IDF framework, and OpenAI Vision/Q&A written in Arduino IDE. Initial testing reveals the two SDKs use fundamentally different approaches. Lalith starts with audio input testing — getting the ESP32 to record and send audio to OpenAI's Whisper API. Postman testing works fine, but ESP32 implementation throws errors. The debugging grind begins.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Ashok Jaiswal', 'Lalith Kumar'],
    messageCount: 25,
    pillar: 'build_in_public',
    tags: ['firmware', 'esp32', 'openai', 'esp_idf', 'arduino', 'audio', 'debugging'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 19,
    date: '2025-08-09',
    dateLabel: 'August 9, 2025',
    title: 'Day 19: OpenAI Image Q&A Working — Robot Can See!',
    summary: `Major breakthrough: Lalith gets the OpenAI Image Question & Answer system working on the ESP32! The user can press "Start Recording," speak a question, press "Stop Recording," and the audio plus a camera image are sent to OpenAI. The answer is transcribed and can be played through the speaker. The robot can literally see its environment and answer questions. Two web UI pages are built: start/stop recording, and firmware mode toggle (ESP-ROLL vs OpenAI QA). A live stream window with game controller overlay is added for manual driving.`,
    mediaFiles: [
      '00000266-VIDEO-2025-09-04-15-09-39.mp4',
      '00000288-PHOTO-2025-09-05-15-07-07.jpg',
      '00000289-PHOTO-2025-09-05-15-07-07.jpg',
    ],
    mediaTypes: ['video', 'image'],
    participants: ['Ashok Jaiswal', 'Lalith Kumar'],
    messageCount: 25,
    pillar: 'product_showcase',
    tags: ['openai', 'vision', 'qna', 'breakthrough', 'web_ui', 'camera', 'speaker'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 20,
    date: '2025-08-10',
    dateLabel: 'August 10, 2025',
    title: 'Day 20: Web Controller UI + GitHub Push',
    summary: `Lalith adds new web pages to the firmware: start/stop recording for OpenAI Q&A, and a firmware toggle between ESP-ROLL and OpenAI QA modes. UI screenshots shared with the team. Ashok asks Lalith to set up a GitHub handle and push the code — maintaining version control is critical. Lalith's GitHub handle is shared (Lalith1011). Ashok sends a repo invite, and Lalith pushes the OpenAI QA firmware code within minutes. Weekly progress report process is established — the team will update every Monday.`,
    mediaFiles: [
      '00000288-PHOTO-2025-09-05-15-07-07.jpg',
      '00000289-PHOTO-2025-09-05-15-07-07.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Lalith Kumar', 'Prithu Hazarika'],
    messageCount: 30,
    pillar: 'build_in_public',
    tags: ['web_ui', 'github', 'firmware', 'openai_qa', 'progress_report'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 24,
    date: '2025-08-14',
    dateLabel: 'August 14, 2025',
    title: 'Day 24: Components Arrive + Audio-Vision Integration',
    summary: `Lalith confirms all required components for the ESP-32 Ball project have arrived. Photos of the components shared — they look different and fewer than what Ashok originally sent. Battery appears too large, and there's no PCBA visible. Lalith clarifies these parts are from the ESP-BALL ROBOT project and will be tested anyway. The OpenAI Image QA is now working with the response played through the speaker — text-to-speech integration is live. Ashok requests a full video recording of the feature in action.`,
    mediaFiles: [
      '00000299-PHOTO-2025-09-06-14-11-14.jpg',
      '00000122-PHOTO-2025-08-23-06-25-27.jpg',
      '00000123-PHOTO-2025-08-23-06-25-27.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Lalith Kumar'],
    messageCount: 15,
    pillar: 'build_in_public',
    tags: ['components', 'arrival', 'speaker', 'tts', 'video_demo', 'testing'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 48,
    date: '2025-09-07',
    dateLabel: 'September 7, 2025',
    title: 'Day 48: Sourcing Crisis — The 100mm Transparent Ball',
    summary: `Prithu shares a sourcing nightmare: the 100mm transparent clear spherical enclosure cannot be found anywhere in India. The team tried every domestic site, searched "christmas decor ball transparent clear 100mm" and similar keywords — nothing. Prithu asks Ashok for help sourcing, suggesting a friend visiting from overseas could bring 15 pieces. This becomes a critical bottleneck. Ashok confirms he'll send parts with a friend traveling to Kerala. The team is advised to focus on PCBA design work while the enclosure sourcing is resolved.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika'],
    messageCount: 8,
    pillar: 'build_in_public',
    tags: ['sourcing', 'transparent_ball', 'india', 'bottleneck', 'manufacturing'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 50,
    date: '2025-09-09',
    dateLabel: 'September 9, 2025',
    title: 'Day 50: Parts Shipped to Hyderabad + Assembly Begins',
    summary: `Ashok ships all ESP-32 ball PCBA components to Hyderabad via a friend (Rakesh Raparthi). Photo of the packed components shared. He asks Prithu's team to assemble at least 2 units and send them back. Motor drivers are missing due to typhoon delays. Ashok shares Rakesh's contact info (VCF file) for pickup coordination. The team is told to focus on PCBA soldering first — the mechanical assembly can be refined later. The spherical enclosures (only 2 available) are given to Prithu's team to keep.`,
    mediaFiles: [
      '00000322-PHOTO-2025-09-09-13-01-57.jpg',
      '00000329-Rakesh Raparthi.vcf',
      '00000335-PHOTO-2025-09-09-13-44-42.jpg',
    ],
    mediaTypes: ['image', 'document'],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Sumit Dandekar', 'Rakesh Raparthi'],
    messageCount: 20,
    pillar: 'manufacturing',
    tags: ['shipping', 'hyderabad', 'assembly', 'components', 'motor_driver', 'typhoon'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 59,
    date: '2025-09-18',
    dateLabel: 'September 18, 2025',
    title: 'Day 59: First Prototype Assembled — It Moves!',
    summary: `BREAKTHROUGH: Prithu's team assembles the first ESP-ROLL unit. It's held together with tape, glue, and adhesives — but it MOVES. The prototype has a 1000mAh battery (must be carried in hand luggage only). Additional weights added for stability. Ashok notes the need for more weight to prevent bobbling. Sumit clarifies the motor driver IC situation — they had to desolder one module and use it on the prototype because of the wrong part number received (DRV8834 instead of DRV8833). The unit is sent back to Hong Kong via Rakesh. Ashok is thrilled — "This is good enough for me to demo."`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Sumit Dandekar'],
    messageCount: 18,
    pillar: 'prototype',
    tags: ['first_prototype', 'assembly', 'tape_glue', 'motor_driver', 'working', 'breakthrough'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 60,
    date: '2025-09-20',
    dateLabel: 'September 20, 2025',
    title: 'Day 60: Major Design Pivot — All Mechanical Parts From Scratch',
    summary: `Critical decision: After assembling the ESP-ROLL prototype, Prithu's team determines the open-source 3D files are "near impossible" to build upon. The decision is made to design ALL mechanical plastic parts from scratch. This is a significant scope change requiring additional budget. Current 3D designs are shared in the group. Ameya Mistry's industrial design work becomes even more critical. Ashok acknowledges the pivot and thanks Prithu for the transparency. The project timeline adjusts to accommodate this fundamental redesign.`,
    mediaFiles: ['00000443-PHOTO-2025-09-20-21-43-26.jpg'],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika'],
    messageCount: 5,
    pillar: 'design',
    tags: ['pivot', 'mechanical_redesign', 'from_scratch', '3d_parts', 'scope_change'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 63,
    date: '2025-09-23',
    dateLabel: 'September 23, 2025',
    title: 'Day 63: New 3D Printed Parts Arrive',
    summary: `First 3D printed parts from the new custom mechanical design arrive. Prithu shares photos and a video of the printed components. The parts show significant improvement over the adapted open-source design. This marks a major milestone — the project now has its own mechanical identity, not derived from someone else's design.`,
    mediaFiles: [
      '00000447-PHOTO-2025-09-23-16-54-22.jpg',
      '00000448-VIDEO-2025-09-23-16-54-22.mp4',
    ],
    mediaTypes: ['image', 'video'],
    participants: ['Prithu Hazarika'],
    messageCount: 4,
    pillar: 'prototype',
    tags: ['3d_printing', 'new_design', 'mechanical', 'parts', 'video'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 67,
    date: '2025-09-27',
    dateLabel: 'September 27, 2025',
    title: 'Day 67: PCBA Design Review + Schematics Shared',
    summary: `Prithu shares the PCBA block diagram and design reference documents with Ashok so he can verify all features are covered. The schematics include: ESP32 controller, motor drivers, power management, camera interface, sensor connections, and display driver. Ashok reviews the design and questions specific implementation details. Sumit is asked to share more detailed technical information. This is the critical review stage before manufacturing.`,
    mediaFiles: [
      '00000456-PHOTO-2025-09-27-22-49-33.jpg',
      '00000457-PHOTO-2025-09-27-22-50-25.jpg',
      '00000459-PHOTO-2025-09-27-23-24-02.jpg',
      '00000460-PHOTO-2025-09-27-23-24-03.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Sumit Dandekar'],
    messageCount: 8,
    pillar: 'product_showcase',
    tags: ['pcba', 'schematics', 'block_design', 'review', 'manufacturing'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 71,
    date: '2025-10-01',
    dateLabel: 'October 1, 2025',
    title: 'Day 71: PCBA Layout Finalized + Manufacturing Begins',
    summary: `Lalith confirms the PCBA layout and design are complete. Component procurement is ongoing. PCB boards have been ordered, and mechanical design components for 10 units are being sourced. The project is now moving from prototyping to small-batch manufacturing. The team is building 10 units — a significant step toward the eventual Kickstarter campaign.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Lalith Kumar'],
    messageCount: 3,
    pillar: 'manufacturing',
    tags: ['pcba', 'manufacturing', 'procurement', '10_units', 'small_batch'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 72,
    date: '2025-10-02',
    dateLabel: 'October 2, 2025',
    title: 'Day 72: Custom PCBA Component Placement Complete',
    summary: `Sumit shares the component placement design and 3D model of the custom PCBA on Autodesk (a360 link). The design includes all required modules: ESP32, motor drivers, camera interface, power management, sensors. The PCB is about to be sent for manufacturing. Ashok reviews and approves the design: "This is good design." The project now has a purpose-built circuit board, not a collection of dev boards wired together.`,
    mediaFiles: [
      '00000472-PHOTO-2025-10-02-02-19-09.jpg',
      '00000473-PHOTO-2025-10-02-02-26-01.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Sumit Dandekar', 'Ashok Jaiswal'],
    messageCount: 4,
    pillar: 'manufacturing',
    tags: ['custom_pcba', 'component_placement', 'manufacturing', 'approved'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 82,
    date: '2025-10-12',
    dateLabel: 'October 12, 2025',
    title: 'Day 82: Assembly Line Photos — Building in Volume',
    summary: `Prithu and Venky share extensive assembly photos — the team is now building units in volume. Multiple photos show: PCBA soldering, motor assembly, battery placement, 3D-printed enclosure parts, and full unit assembly. Venky uploads 20+ photos showing the step-by-step assembly process. This is the first real production run. The photos are specifically captured for social media — Ashok had requested build documentation content. Prithu encourages Venky to keep sharing process photos for the community.`,
    mediaFiles: [
      '00000485-PHOTO-2025-10-12-17-19-14.jpg',
      '00000486-PHOTO-2025-10-12-17-19-15.jpg',
      '00000487-PHOTO-2025-10-12-17-19-16.jpg',
      '00000489-PHOTO-2025-10-12-17-23-37.jpg',
      '00000490-PHOTO-2025-10-12-17-23-38.jpg',
      '00000493-PHOTO-2025-10-12-17-37-00.jpg',
      '00000494-PHOTO-2025-10-12-17-37-01.jpg',
      '00000495-PHOTO-2025-10-12-17-37-02.jpg',
      '00000496-PHOTO-2025-10-12-17-37-02.jpg',
      '00000497-PHOTO-2025-10-12-17-37-03.jpg',
      '00000498-PHOTO-2025-10-12-17-37-04.jpg',
      '00000499-PHOTO-2025-10-12-17-37-05.jpg',
      '00000500-PHOTO-2025-10-12-17-37-05.jpg',
      '00000501-PHOTO-2025-10-12-17-37-06.jpg',
      '00000502-PHOTO-2025-10-12-17-37-09.jpg',
      '00000504-PHOTO-2025-10-12-20-46-47.jpg',
      '00000505-PHOTO-2025-10-12-20-46-48.jpg',
      '00000506-PHOTO-2025-10-12-20-46-48.jpg',
      '00000507-PHOTO-2025-10-12-20-46-49.jpg',
      '00000508-PHOTO-2025-10-12-20-46-50.jpg',
      '00000509-PHOTO-2025-10-12-20-46-50.jpg',
      '00000510-PHOTO-2025-10-12-20-46-53.jpg',
      '00000511-PHOTO-2025-10-12-20-46-58.jpg',
      '00000512-PHOTO-2025-10-12-20-46-59.jpg',
      '00000513-PHOTO-2025-10-12-20-47-00.jpg',
      '00000514-PHOTO-2025-10-12-20-47-02.jpg',
      '00000515-PHOTO-2025-10-12-20-47-03.jpg',
      '00000516-PHOTO-2025-10-12-20-47-03.jpg',
      '00000517-PHOTO-2025-10-12-20-47-04.jpg',
      '00000518-PHOTO-2025-10-12-20-47-05.jpg',
      '00000519-PHOTO-2025-10-12-20-47-06.jpg',
      '00000520-PHOTO-2025-10-12-20-47-06.jpg',
      '00000521-PHOTO-2025-10-12-20-47-07.jpg',
      '00000522-PHOTO-2025-10-12-20-47-08.jpg',
      '00000523-PHOTO-2025-10-12-20-47-09.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Prithu Hazarika', 'Venky'],
    messageCount: 45,
    pillar: 'manufacturing',
    tags: ['assembly', 'volume', 'photos', 'production', 'pcba_soldering', 'social_media'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 83,
    date: '2025-10-13',
    dateLabel: 'October 13, 2025',
    title: 'Day 83: More Assembly Photos + Firmware Testing Videos',
    summary: `Lalith shares more assembly photos (8 images) and the team continues testing. The firmware testing shows improved stability compared to the earlier tape-and-glue prototype. Videos are shared showing the robot moving more smoothly. Ashok is pleased: "This is so much more stable." The distance and temperature sensor integration is discussed — the firmware team confirms basic communication with these sensors is established but full integration is still in progress.`,
    mediaFiles: [
      '00000525-PHOTO-2025-10-13-19-12-13.jpg',
      '00000526-PHOTO-2025-10-13-19-12-13.jpg',
      '00000527-PHOTO-2025-10-13-19-12-13.jpg',
      '00000528-PHOTO-2025-10-13-19-12-14.jpg',
      '00000529-PHOTO-2025-10-13-19-12-14.jpg',
      '00000530-PHOTO-2025-10-13-19-12-14.jpg',
      '00000531-PHOTO-2025-10-13-19-12-15.jpg',
      '00000532-PHOTO-2025-10-13-19-12-15.jpg',
      '00000533-PHOTO-2025-10-13-19-12-15.jpg',
      '00000534-PHOTO-2025-10-13-19-12-15.jpg',
      '00000543-VIDEO-2025-10-14-21-56-13.mp4',
      '00000544-VIDEO-2025-10-14-21-56-13.mp4',
    ],
    mediaTypes: ['image', 'video'],
    participants: ['Lalith Kumar', 'Ashok Jaiswal'],
    messageCount: 15,
    pillar: 'build_in_public',
    tags: ['assembly', 'testing', 'stability', 'sensor', 'distance', 'temperature'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 87,
    date: '2025-10-17',
    dateLabel: 'October 17, 2025',
    title: 'Day 87: First Units Ship to Hong Kong via Courier',
    summary: `Lalith couriers 2 assembled units to Ashok's home in Delhi via DTDC. The shipment confirmation photo is shared. Speakers haven't arrived yet — a connector is provided for Ashok to solder. The temperature sensor is missing from both boards because the received modules were faulty and had to be replaced. Lalith promises to assemble all remaining units by the following Tuesday. Ashok shares his address in Noida and phone number for the courier. A competitor video is also shared (KEYI Technology update).`,
    mediaFiles: [
      '00000560-PHOTO-2025-10-17-17-19-17.jpg',
      '00000555-PHOTO-2025-10-15-09-53-52.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Lalith Kumar', 'Ashok Jaiswal'],
    messageCount: 10,
    pillar: 'manufacturing',
    tags: ['courier', 'shipping', 'dtdc', 'hong_kong', 'delhi', 'speakers', 'faulty_parts'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 89,
    date: '2025-10-19',
    dateLabel: 'October 19, 2025',
    title: 'Day 89: Demo Video from India + Courier Tracking',
    summary: `Prithu shares a demo video of the latest prototype. Ashok provides the DTDC courier tracking link and ID (V3500684991) so the team can monitor shipment progress. The prototype video shows significant progress in stability and movement. The team is now moving toward having working units available for demonstrations.`,
    mediaFiles: [
      '00000570-VIDEO-2025-10-19-19-41-11.mp4',
      '00000577-PHOTO-2025-10-20-13-44-52.jpg',
      '00000580-PHOTO-2025-10-20-13-53-38.jpg',
    ],
    mediaTypes: ['video', 'image'],
    participants: ['Prithu Hazarika', 'Lalith Kumar', 'Ashok Jaiswal'],
    messageCount: 10,
    pillar: 'product_showcase',
    tags: ['demo', 'video', 'tracking', 'courier', 'prototype'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 102,
    date: '2025-11-01',
    dateLabel: 'November 1, 2025',
    title: 'Day 102: 355 Build Photos — Our Visual Journey',
    summary: `A milestone in documentation: The WhatsApp archive now contains 355+ build photos documenting the entire journey from day one. These photos tell the story of PawMe's evolution: from components spread on a table, to first firmware flash, to rough prototype moving across the floor, to custom PCBA, to the beginning of industrial design. This visual archive is what will power the Kickstarter campaign and the community timeline.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Ashok Jaiswal'],
    messageCount: 2,
    pillar: 'founder_voice',
    tags: ['355_photos', 'documentation', 'visual_journey', 'archive'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 112,
    date: '2025-11-11',
    dateLabel: 'November 11, 2025',
    title: 'Day 112: Kickstarter Video Shoot Planning',
    summary: `Prithu shares the detailed shot list for the Kickstarter video. The plan includes shooting two takes of each scene. Reference video structure is analyzed shot-by-shot. The team plans to shoot on mobile phones (not professional equipment) with editing done separately. An intern is also discussed to help with social media posting. The video will have 6 parts: Intro, Product Overview, Design Process, Electronics & Firmware, Manufacturing & Assembly, and Final Reveal.`,
    mediaFiles: ['00000776-PHOTO-2025-11-12-19-51-27.jpg'],
    mediaTypes: ['image'],
    participants: ['Prithu Hazarika', 'Ashok Jaiswal'],
    messageCount: 6,
    pillar: 'media',
    tags: ['kickstarter', 'video', 'shot_list', 'planning', '6_parts'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 113,
    date: '2025-11-12',
    dateLabel: 'November 12, 2025',
    title: 'Day 113: Kickstarter Video Shoot Day 1',
    summary: `The team begins shooting the Kickstarter video. Multiple video clips are recorded. Ambient noise is identified as a challenge — the team plans to add music in post-production (the same approach used in successful reference campaigns). Videos are uploaded to a shared Google Drive folder. Prithu mentions that video editing is NOT in their scope — this will need to be done at Ashok's end. Minor changes are still possible after today, but major restructuring will be difficult.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Prithu Hazarika', 'Ashok Jaiswal'],
    messageCount: 12,
    pillar: 'media',
    tags: ['kickstarter', 'video', 'shooting', 'ambient_noise', 'music', 'google_drive'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 114,
    date: '2025-11-13',
    dateLabel: 'November 13, 2025',
    title: 'Day 114: Video Review + Audio Fixes',
    summary: `Prithu shares the first video footage for review. Ashok likes the mechanical explanation but notes audio quality needs improvement on two clips. Lalith is asked to re-record the audio. The ambient noise issue is acknowledged — the team recommends adding background music (same approach as the reference Kickstarter videos). A detailed video shoot plan discussion is scheduled between Ashok and Lalith.`,
    mediaFiles: [
      '00000711-VIDEO-2025-11-02-19-03-21.mp4',
    ],
    mediaTypes: ['video'],
    participants: ['Prithu Hazarika', 'Ashok Jaiswal', 'Lalith Kumar'],
    messageCount: 10,
    pillar: 'media',
    tags: ['video', 'review', 'audio', 'footage', 're_shoot'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 118,
    date: '2025-11-17',
    dateLabel: 'November 17, 2025',
    title: 'Day 118: Ameya Mistry Joins + Design Sync',
    summary: `Ameya Mistry is added to the group! He's the industrial designer who will be working on PawMe's form factor and aesthetics. Prithu shares the Miro board for Ameya's reference. Ameya schedules a design sync meeting via Google Meet. The agenda: discuss process, timeline, check points, and key deliverables. During the call, the team discusses a critical question: "How do we define what success means for this project?" The answer: a successful Kickstarter campaign. What makes a successful Kickstarter? VIRALITY. What makes it viral? Making the product so cool that people can't help but share it. For the first time, this research feeds directly into feature decisions for the prototype.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Ameya Mistry', 'Lalith Kumar', 'Hitesh Suthar'],
    messageCount: 15,
    pillar: 'design',
    tags: ['ameya_mistry', 'joins', 'design_sync', 'kickstarter', 'viral', 'success_definition'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 119,
    date: '2025-11-18',
    dateLabel: 'November 18, 2025',
    title: 'Day 119: Kickstarter Video — Review + Audio Fixes Done',
    summary: `Ashok reviews the second batch of Kickstarter video footage. He compliments Prithu's mechanical explanation: "Your mechanical explanation was amazing, well done." However, he notes room for improvement in audio quality for two clips. Lalith confirms he'll redo the audio for the mechanical and assembly parts. The manufacturing and assembly videos are uploaded by Lalith. The OpenAI QA feature demo video is also part of the footage.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Ashok Jaiswal', 'Prithu Hazarika', 'Lalith Kumar'],
    messageCount: 8,
    pillar: 'media',
    tags: ['video', 'review', 'audio_fix', 'manufacturing', 'assembly', 'openai_qa'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 123,
    date: '2025-11-22',
    dateLabel: 'November 22, 2025',
    title: 'Day 123: Video Upload + YouTube Channel Creation',
    summary: `Ashok creates a YouTube channel for PawMe and asks Lalith to upload the video footage there instead of Google Drive (having trouble playing Drive videos). Lalith shares a WeTransfer link for easier file access. The video collection is growing — including videos of: robot components, PCBA assembly, firmware flashing timelapse, mechanical assembly, OpenAI QA feature demo, speaker test, 3D parts, camera setup, SD card setup, electronics design walkthrough, and more.`,
    mediaFiles: [],
    mediaTypes: [],
    participants: ['Lalith Kumar', 'Ashok Jaiswal'],
    messageCount: 5,
    pillar: 'media',
    tags: ['youtube', 'video_upload', 'channel', 'file_sharing', 'media_library'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 149,
    date: '2025-12-18',
    dateLabel: 'December 18, 2025',
    title: 'Day 149: Ameya\'s Design Explorations — Dead of Night at 5 AM',
    summary: `Ameya Mistry shares a flurry of design photos at 5 AM — 12 images showing various head shapes, body proportions, and front face designs for PawMe. The designs show significant progress on the industrial design front. Different head shapes are explored: spherical, cylindrical, and hybrid forms. The dot matrix LED face is visible in several renderings. This late-night Ameya session shows the passion and dedication going into making PawMe's design special.`,
    mediaFiles: [
      '00001069-PHOTO-2025-12-18-03-03-36.jpg',
      '00001070-PHOTO-2025-12-18-05-00-34.jpg',
      '00001071-PHOTO-2025-12-18-05-00-35.jpg',
      '00001072-PHOTO-2025-12-18-05-00-51.jpg',
      '00001073-PHOTO-2025-12-18-05-00-52.jpg',
      '00001074-PHOTO-2025-12-18-05-01-13.jpg',
      '00001075-PHOTO-2025-12-18-05-01-14.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ameya Mistry'],
    messageCount: 8,
    pillar: 'design',
    tags: ['amexa', 'design', 'early_morning', 'renderings', 'head_design', 'dot_matrix'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 150,
    date: '2025-12-19',
    dateLabel: 'December 19, 2025',
    title: 'Day 150: Design Critique — Monochrome + Single Color Body',
    summary: `Prithu shares his favorite design renderings and opens the floor for feedback. Key discussion points:\n\n→ Head color: Prithu is "not very fond of having the head in a different colour." The team agrees monochrome is cleaner.\n→ Body color: Hitesh suggests full body in a single color. "The display can omit any type of light so remaining body should be just one/mono coloured, keeping the aesthetics clean."\n→ Display type: Monochrome-DotMatrix is confirmed. RGD DotMatrix was discussed but is more expensive.\n→ Red strap/pony-tail: Ameya proposes a small red accent element that becomes a branding tag — a consistent element across all PawMe products.\n→ Cylindrical concept: Ashok asks Ameya to try a cylindrical shape for the charging/dispenser assembly.\n\nThe design is converging. The team is making real decisions, not just exploring.`,
    mediaFiles: [
      '00001080-PHOTO-2025-12-19-06-22-20.jpg',
      '00001081-PHOTO-2025-12-19-06-22-21.jpg',
      '00001082-PHOTO-2025-12-19-06-22-43.jpg',
      '00001083-PHOTO-2025-12-19-06-22-45.jpg',
      '00001084-PHOTO-2025-12-19-06-23-30.jpg',
      '00001085-PHOTO-2025-12-19-06-23-31.jpg',
      '00001088-PHOTO-2025-12-19-06-26-13.jpg',
      '00001089-PHOTO-2025-12-19-06-26-13.jpg',
      '00001090-PHOTO-2025-12-19-12-45-00.jpg',
      '00001091-PHOTO-2025-12-19-12-46-13.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ameya Mistry', 'Ashok Jaiswal', 'Prithu Hazarika', 'Hitesh Suthar'],
    messageCount: 15,
    pillar: 'design',
    tags: ['design_critique', 'monochrome', 'single_color', 'red_strap', 'cylindrical', 'dot_matrix'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 155,
    date: '2025-12-24',
    dateLabel: 'December 24, 2025',
    title: 'Day 155: Christmas Eve Design Session — 11 PM Iteration',
    summary: `At 11 PM on Christmas Eve, the team is still working. Ameya shares more renderings of the cylindrical charging dock concept. Debate: cylindrical looks "classier" but Ashok notes it would be "a bit more bulkier" and take more floor space. Decision: Keep the current design. The cylindrical was an interesting exploration but adds unnecessary volume. Prithu syncs with Ameya on the final direction. The red accent/pony-tail is kept as a branding element. This is the reality of a startup — nobody stops for Christmas when there's a product to build.`,
    mediaFiles: [
      '00001101-PHOTO-2025-12-20-01-48-59.jpg',
      '00001102-PHOTO-2025-12-20-01-49-00.jpg',
      '00001105-PHOTO-2025-12-21-21-14-56.jpg',
      '00001106-PHOTO-2025-12-21-21-14-58.jpg',
      '00001130-PHOTO-2025-12-24-22-53-28.jpg',
      '00001131-PHOTO-2025-12-24-22-53-51.jpg',
      '00001132-PHOTO-2025-12-24-22-54-05.jpg',
      '00001134-PHOTO-2025-12-24-22-54-20.jpg',
      '00001140-PHOTO-2025-12-24-23-00-35.jpg',
      '00001141-PHOTO-2025-12-24-23-01-38.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ameya Mistry', 'Ashok Jaiswal', 'Prithu Hazarika'],
    messageCount: 18,
    pillar: 'design',
    tags: ['christmas_eve', 'late_night', 'design_iteration', 'charging_dock', 'final_design'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 185,
    date: '2026-01-23',
    dateLabel: 'January 23, 2026',
    title: 'Day 185: Manufacturing Photos + Progress Update',
    summary: `Lalith and the team share manufacturing progress photos. The assembly line is running with multiple units in various states of completion. The photos show: finished PCBAs, assembled motor units, battery integration, and head mechanism testing. The firmware is being updated to support the new custom PCBA layout. Ashok receives the latest batch and notes improvements in build quality.`,
    mediaFiles: [
      '00001305-PHOTO-2026-01-21-14-32-12.jpg',
      '00001235-PHOTO-2025-12-31-14-04-17.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Lalith Kumar', 'Ashok Jaiswal'],
    messageCount: 8,
    pillar: 'manufacturing',
    tags: ['manufacturing', 'batch', 'assembly', 'progress', 'new_year'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 223,
    date: '2026-02-24',
    dateLabel: 'February 24, 2026',
    title: 'Day 223: Camera + LED Face Integration Working',
    summary: `Major milestone: The ESP32-CAM is now fully integrated with the LED matrix face. For the first time, PawMe can "see" and express emotions simultaneously. When the camera detects a face, the head tilts and the LED face shows a happy expression. This is the core magic of PawMe coming together. Ameya shares photos of the latest industrial design with the integrated face display. The robot is starting to look like a product, not a prototype.`,
    mediaFiles: [
      '00001562-PHOTO-2026-02-24-18-22-48.jpg',
      '00001427-PHOTO-2026-02-01-16-39-55.jpg',
      '00001489-PHOTO-2026-02-09-15-25-44.jpg',
      '00001481-PHOTO-2026-02-09-15-25-41.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Ameya Mistry'],
    messageCount: 12,
    pillar: 'prototype',
    tags: ['camera', 'led_face', 'integration', 'face_detection', 'emotions', 'milestone'],
    sourceType: 'whatsapp',
  },
  {
    dayNumber: 228,
    date: '2026-03-01',
    dateLabel: 'March 1, 2026',
    title: 'Day 228: Prototype v4 — First Successful Autonomous Following Test',
    summary: `BREAKTHROUGH: PawMe successfully follows Ashok around the room for the first time! The camera detects his face, the IMU keeps the head level, and the motors track the movement. The LED face shows a happy expression when it "sees" him. This is 8 months of work coming together in one moment. The firmware now supports: face detection → head tracking → smooth movement → emotional expression. The team celebrates this milestone. This is exactly what was envisioned on Day 0.`,
    mediaFiles: [
      '00001506-PHOTO-2026-02-17-01-27-43.jpg',
      '00001512-PHOTO-2026-02-17-02-36-59.jpg',
      '00001056-PHOTO-2025-12-17-01-27-10.jpg',
      '00001037-PHOTO-2025-12-14-21-17-52.jpg',
    ],
    mediaTypes: ['image'],
    participants: ['Ashok Jaiswal', 'Lalith Kumar'],
    messageCount: 6,
    pillar: 'prototype',
    tags: ['autonomous_following', 'face_tracking', 'milestone', 'v4', 'breakthrough'],
    sourceType: 'whatsapp',
  },
];

// Helper to get all media files from the WhatsApp folder
export const WHATSAPP_MEDIA_DIR = 'WhatsApp Chat - Rolling Robot - Pawme';

export function getMediaUrl(filename: string): string {
  // In production, these would be served from Firebase Storage or Google Drive
  // For now, reference the local file path
  return `/media/${filename}`;
}

export function getTotalDays(): number {
  if (TIMELINE_DAYS.length === 0) return 0;
  return Math.max(...TIMELINE_DAYS.map(d => d.dayNumber));
}

export function getMediaCount(): number {
  return TIMELINE_DAYS.reduce((sum, d) => sum + d.mediaFiles.length, 0);
}
